export default {
  IS_LOGGED_IN: "IS_LOGGED_IN",
  IS_LOADING: "IS_LOADING",
  TOGGLE_MOBILE_MENU: "TOGGLE_MOBILE_MENU",
  
  // initial data load
  GET_EMPLOYEES: "GET_EMPLOYEES",
  GET_PRODUCTS: "GET_PRODUCTS",
  
  SHORT_MENU: "SHORT_MENU",
  SET_SIDE_BAR: "SET_SIDE_BAR",
  SET_SIDE_BAR_OPTION: "SET_SIDE_BAR_OPTION",
  SET_EMPLOYEES: "SET_EMPLOYEES",
  SET_PRODUCTS: "SET_PRODUCTS",
  TOGGLE_DOWNLOAD_SCREEN: "TOGGLE_DOWNLOAD_SCREEN",

  // timesheet
  SET_CLOCK_IN_INPUT_VALUE: "SET_CLOCK_IN_INPUT_VALUE",
  SET_CLOCK_IN_SELECTED_EMPLOYEE: "SET_CLOCK_IN_SELECTED_EMPLOYEE",
  SELECTED_EMPLOYEE_IS_CLOCKED_IN: "SELECTED_EMPLOYEE_IS_CLOCKED_IN",
  SET_TOTAL_HOURS: "SET_TOTAL_HOURS",
  SET_WEEK_NUMBER: "SET_WEEK_NUMBER",

  // employee directory
  TOGGLE_EMPLOYEE_EDITING_STATUS: "TOGGLE_EMPLOYEE_EDITING_STATUS",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  UPDATE_EMPLOYEE_TABLE_OFFSET: "UPDATE_EMPLOYEE_TABLE_OFFSET",
  UPDATE_EMPLOYEE_TABLE_LIMIT: "UPDATE_EMPLOYEE_TABLE_LIMIT",
  SET_EMPLOYEES_COUNT: "SET_EMPLOYEES_COUNT",

  // point of sale
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  SET_CART_ITEMS: "SET_CART_ITEMS",
  ADJUST_ITEM_QUANTITY: "ADJUST_ITEM_QUANTITY",

  // transactions
  SET_PAYMENT_LIST: "SET_PAYMENT_LIST",
  SET_ITEMS_PURCHASED: "SET_ITEMS_PURCHASED",
  SET_PAYMENT_ID: "SET_PAYMENT_ID",
}
