export default {
  // SET
  SET_SELECTED_ITEMS: "SET_SELECTED_ITEMS",
  SET_EMPLOYEES: "SET_EMPLOYEES",
  SET_LABOR_TYPES: "SET_LABOR_TYPES",
  SET_JOB_NUMBERS: "SET_JOB_NUMBERS",

  // CREATE
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  CREATE_LABOR_TYPE: "CREATE_LABOR_TYPE",
  CREATE_JOB_NUMBER: "CREATE_JOB_NUMBER",


  // DELETE
  BULK_DELETE: "BULK_DELETE",



  CLOCK_IN: "CLOCK_IN",
  CLOCK_OUT: "CLOCK_OUT",
  GO_TO_LUNCH: "GO_TO_LUNCH",
  BACK_FROM_LUNCH: "BACK_FROM_LUNCH",
  BULK_DEACTIVATE: "BULK_DEACTIVATE",
  BULK_ACTIVATE: "BULK_ACTIVATE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  TOGGLE_ADMIN_MODE: "TOGGLE_ADMIN_MODE",
  OPEN_MESSAGE: "OPEN_MESSAGE",
  CLOSE_MESSAGE: "CLOSE_MESSAGE",
  TOGGLE_DOWNLOAD_SCREEN: "TOGGLE_DOWNLOAD_SCREEN",
  TOGGLE_IS_CONTRACTOR: "TOGGLE_IS_CONTRACTOR",
  TOGGLE_IS_TECH: "TOGGLE_IS_TECH",
  CLEAR_CSV_DATA: "CLEAR_CSV_DATA",
  GET_CSV_DATA: "GET_CSV_DATA",
  SET_CSV_DATA: "SET_CSV_DATA",
  LOG_IN: "LOG_IN"

}
