export default {
  SHORT_MENU: "SHORT_MENU",
  SET_SIDE_BAR: "SET_SIDE_BAR",
  SET_SIDE_BAR_OPTION: "SET_SIDE_BAR_OPTION",
  SET_EMPLOYEES: "SET_EMPLOYEES",
  TOGGLE_DOWNLOAD_SCREEN: "TOGGLE_DOWNLOAD_SCREEN",
  CLOCK_IN_EMPLOYEE: "CLOCK_IN_EMPLOYEE"
}
