export default {
  IS_LOADING: "IS_LOADING",
  
  // initial data load
  GET_EMPLOYEES: "GET_EMPLOYEES",
  
  SHORT_MENU: "SHORT_MENU",
  SET_SIDE_BAR: "SET_SIDE_BAR",
  SET_SIDE_BAR_OPTION: "SET_SIDE_BAR_OPTION",
  SET_EMPLOYEES: "SET_EMPLOYEES",
  TOGGLE_DOWNLOAD_SCREEN: "TOGGLE_DOWNLOAD_SCREEN",

  // timesheet
  SET_CLOCK_IN_INPUT_VALUE: "SET_CLOCK_IN_INPUT_VALUE",
  SET_CLOCK_IN_SELECTED_EMPLOYEE: "SET_CLOCK_IN_SELECTED_EMPLOYEE",
  SELECTED_EMPLOYEE_IS_CLOCKED_IN: "SELECTED_EMPLOYEE_IS_CLOCKED_IN",

  // employee directory
  TOGGLE_EMPLOYEE_EDITING_STATUS: "TOGGLE_EMPLOYEE_EDITING_STATUS",
}
